### PR TITLE
Decoding condition (#13)

### PR DESCRIPTION
**Pull request by s1lver**
See describe issue #13

### CODE REVIEW

**Comment by roopan-sellanyhome** [comment]
@s1lver  Merged with master branch

**Comment by yiioverflow** [comment]
@s1lver Thanks!

**Comment by dima-sdi** [comment]
Now got error
Error: Undefined index: decodeMimeStr

**Comment by yiioverflow** [comment]
@s1lver can you check this pls ?

**Comment by s1lver** [comment]
@dima-sdi Please give more details. Please note that there is a new setting  `decodeMimeStr`

**Comment by s1lver** [comment]
@yiioverflow I confirm full working capacity for several months now

**Comment by dima-sdi** [comment]
@s1lver Look like I've missed a new setting. This update totally broke my production ) May be you should make this setting to be optional?
BTW, @yiioverflow your blog http://blog.yiioverflow.com/yii2-imap is also broken for few days 
Anyway, thank you for this lib -  I really like to use it )

**Comment by s1lver** [comment]
@yiioverflow @dima-sdi I confirm my work. 
It is necessary to add a configuration to the config. 
```
[
 'imap' => ['class' => ..., 'connection' => ['decodingMimeStr' => false]]
]
```

In the near future I will do a pull request.

**Comment by s1lver** [comment]
@yiioverflow Please see #16

**Pull request merged**
